package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"io"

	"github.com/99designs/gqlgen/graphql"
	"github.com/looplj/axonhub/internal/server/biz"
	"github.com/samber/lo"
)

// Backup is the resolver for the backup field.
func (r *mutationResolver) Backup(ctx context.Context, input biz.BackupOptions) (*BackupPayload, error) {
	data, err := r.backupService.Backup(ctx, input)
	if err != nil {
		return nil, err
	}

	dataStr := string(data)

	return &BackupPayload{
		Success: true,
		Data:    &dataStr,
		Message: lo.ToPtr("Backup completed successfully"),
	}, nil
}

// Restore is the resolver for the restore field.
func (r *mutationResolver) Restore(ctx context.Context, file graphql.Upload, input biz.RestoreOptions) (*RestorePayload, error) {
	fileContent, err := io.ReadAll(file.File)
	if err != nil {
		return nil, err
	}

	err = r.backupService.Restore(ctx, fileContent, input)
	if err != nil {
		return nil, err
	}

	return &RestorePayload{
		Success: true,
		Message: lo.ToPtr("Restore completed successfully"),
	}, nil
}
